#spring:
#  cloud:
##    gateway:
##
##      routes:
##        - id: r1
##          uri: lb://CUSTOMER-SERVICE
##          predicates:
##            - Path= /customers/**
##        - id: r2
##          uri: lb://INVENTORY-SERVICE
##          predicates:
##            - Path= /products/**
#    config:
#      enabled: false
#    gateway:
#      discovery:
#        locator:
#          lower-case-service-id: true
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
#    fetchRegistry: true
#    registerWithEureka: true
#  instance:
#    preferIpAddress: true
#server:
#  port: 9989
